"""
tests/integration/test_syslog_demo_pipeline.py

ULPF Demo Pipeline Integration Test — syslog-demo-001

This test exercises the COMPLETE ULPF pipeline for the synthetic demo fixture:

    Source Profile Registration → Raw Ingestion → Format Detection →
    Parsing → Source Context Injection → OCSF Mapping →
    OCSF 1.3.0 Validation (PASS) → Provenance → Integrity → Replay

IMPORTANT DESIGN NOTES
-----------------------
1.  syslog-demo-001 is a SYNTHETIC fixture.
    It is NOT the historical syslog-001 dataset.
    Its source context (capture_year, capture_timezone, vendor_name,
    product_name) is intentionally and completely specified for demonstration.

2.  syslog-001 remains the REAL historical fixture.
    It is intentionally left UNREGISTERED to honestly reflect the absence
    of authoritative capture metadata for that dataset.

3.  The expected OCSF validation result for syslog-demo-001 is PASS
    because all required fields (time, metadata.product.vendor_name)
    are provided by the authoritative demo Source Profile.

DEMO SOURCE PROFILE — syslog-demo-001:1.0.0
    capture_year:      2026
    capture_timezone:  UTC
    vendor_name:       Linux
    product_name:      iptables

    These values apply ONLY to syslog-demo-001.
    They are NOT authoritative metadata for the historical syslog-001 dataset.

GROUND TRUTH
    Ground truth was authored manually BEFORE running this test.
    File: fixtures/ground_truth/syslog/syslog-demo-001.json
    Timestamps were computed analytically: for each RFC3164 event,
    capture_year=2026 + RFC3164 month/day/time + capture_timezone=UTC.
    Vendor/product values were sourced only from the declared Source Profile.
    The ground truth was NOT generated by running the parser and copying output.
"""

import hashlib
import json
import tempfile
from pathlib import Path

import pytest

from src.ingestion.ingestor import ingest_bytes, split_raw_records, strip_record_terminator
from src.normalization.mapper import OCSFMapper, MappingResult
from src.normalization.ocsf_validator import OCSFValidationResult
from src.parsers.engine import ParserEngine
from src.registry import (
    _clear_registry,
    activate_source_profile,
    configure_profile_storage,
    deactivate_source_profile,
    get_historical_source_profile,
    get_source_profile,
    list_source_profiles,
    register_parser,
    register_source_profile,
    ProfileInactiveError,
    ProfileNotFoundError,
    ProfileState,
)
from src.vault import store as vault


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DEMO_FIXTURE_ID = "syslog-demo-001"
DEMO_PROFILE_VERSION = "1.0.0"

DEMO_PROFILE = {
    "source": "syslog-demo-001",
    "profile_version": "1.0.0",
    "capture_year": 2026,
    "capture_timezone": "UTC",
    "vendor_name": "Linux",
    "product_name": "iptables",
}

# SHA-256 of the synthetic raw fixture — must match on every run.
# Computed once from the authored file; this constant guards against
# accidental modification of the raw fixture.
DEMO_FIXTURE_SHA256 = "47b4f899e9a38af719bcddae41eef79a152b4de09cfc06e503bd654547b115e5"
DEMO_FIXTURE_BYTES = 1347
DEMO_EVENT_COUNT = 7

# Manually authored expected timestamps (analytically computed from
# capture_year=2026, capture_timezone=UTC, RFC3164 month/day/time fields).
# These are ground truth — NOT copied from parser output.
EXPECTED_TIMESTAMPS = [
    1788256801,  # Sep  1 10:00:01 UTC 2026
    1788256805,  # Sep  1 10:00:05 UTC 2026
    1788256893,  # Sep  1 10:01:33 UTC 2026
    1788256967,  # Sep  1 10:02:47 UTC 2026
    1788257112,  # Sep  1 10:05:12 UTC 2026
    1788257275,  # Sep  1 10:07:55 UTC 2026
    1788257403,  # Sep  1 10:10:03 UTC 2026
]

POLICY_VALUES = {
    "class_uid": 4001,
    "category_uid": 4,
    "activity_id": 6,
    "type_uid": 400106,
    "severity_id": 1,
}

RAW_FIXTURE_PATH = Path("fixtures/raw/syslog/syslog-demo-001.log").resolve()
GROUND_TRUTH_PATH = Path("fixtures/ground_truth/syslog/syslog-demo-001.json").resolve()
PARSER_PATH = Path("parsers/syslog.yaml").resolve()


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(autouse=True)
def isolated_demo_env(tmp_path):
    """Provide a fully isolated vault and registry for each test."""
    # Isolated vault
    prior_backend = vault._BACKEND
    vault.configure_backend(vault.FileVaultBackend(tmp_path / "demo-vault"))

    # Isolated registry with temp storage
    registry_storage = tmp_path / "demo-registry"
    configure_profile_storage(registry_storage)
    _clear_registry()

    yield

    _clear_registry()
    configure_profile_storage(None)
    vault.configure_backend(prior_backend)


@pytest.fixture()
def registered_demo_profile():
    """Register and activate the demo Source Profile."""
    register_source_profile(
        DEMO_FIXTURE_ID,
        DEMO_PROFILE_VERSION,
        DEMO_PROFILE,
        activate=True,
    )
    return DEMO_PROFILE


@pytest.fixture()
def demo_parser():
    """Register the syslog parser under the demo source_id."""
    register_parser(DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION, str(PARSER_PATH))
    return ParserEngine(DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION)


@pytest.fixture()
def raw_demo_bytes():
    """Load raw fixture bytes and verify integrity before use."""
    with open(RAW_FIXTURE_PATH, "rb") as f:
        raw = f.read()
    sha256 = hashlib.sha256(raw).hexdigest()
    assert sha256 == DEMO_FIXTURE_SHA256, (
        f"Demo fixture SHA-256 mismatch — fixture may have been modified.\n"
        f"Expected: {DEMO_FIXTURE_SHA256}\n"
        f"Actual:   {sha256}"
    )
    assert len(raw) == DEMO_FIXTURE_BYTES, (
        f"Demo fixture byte length mismatch: expected {DEMO_FIXTURE_BYTES}, got {len(raw)}"
    )
    return raw


@pytest.fixture()
def ground_truth():
    """Load manually authored ground truth."""
    with open(GROUND_TRUTH_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


# ---------------------------------------------------------------------------
# TEST 1 — Raw fixture integrity
# ---------------------------------------------------------------------------

def test_demo_fixture_raw_integrity(raw_demo_bytes):
    """Verify raw bytes are the exact authored content — fixture not modified."""
    assert hashlib.sha256(raw_demo_bytes).hexdigest() == DEMO_FIXTURE_SHA256
    assert len(raw_demo_bytes) == DEMO_FIXTURE_BYTES

    lines = [ln for ln in raw_demo_bytes.decode("utf-8").strip().split("\n") if ln.strip()]
    assert len(lines) == DEMO_EVENT_COUNT, (
        f"Expected {DEMO_EVENT_COUNT} events, got {len(lines)}"
    )


# ---------------------------------------------------------------------------
# TEST 2 — Source Profile registration, activation, persistence, and reload
# ---------------------------------------------------------------------------

def test_demo_profile_registration_and_persistence(tmp_path):
    """Register demo profile, verify persistence and reload.

    _clear_registry() is a TEST CLEANUP helper that deletes stored files.
    To simulate a process restart (in-memory state lost but storage intact),
    we zero the in-memory _profile_registry directly and then call
    configure_profile_storage to reload from the durable store.
    """
    import src.registry as reg_module

    storage = tmp_path / "persist-store"
    configure_profile_storage(storage)
    _clear_registry()

    register_source_profile(
        DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION, DEMO_PROFILE, activate=True
    )

    # File persisted in storage
    profile_file = storage / f"{DEMO_FIXTURE_ID}__{DEMO_PROFILE_VERSION}.json"
    assert profile_file.exists(), "Profile JSON file must exist in durable storage"

    # Retrieve via active API
    retrieved = get_source_profile(DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION)
    assert retrieved == DEMO_PROFILE

    # Simulate process restart: zero in-memory state WITHOUT deleting files.
    # This mimics a new process starting up and loading from the durable store.
    reg_module._profile_registry.clear()
    configure_profile_storage(storage)

    # Profile survives reload and is active
    reloaded = get_source_profile(DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION)
    assert reloaded == DEMO_PROFILE

    profiles = list_source_profiles()
    assert (DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION, ProfileState.ACTIVE) in profiles


# ---------------------------------------------------------------------------
# TEST 3 — syslog-001 remains unregistered
# ---------------------------------------------------------------------------

def test_syslog_001_remains_unregistered(registered_demo_profile):
    """Registering demo profile must NOT touch syslog-001."""
    with pytest.raises(ProfileNotFoundError):
        get_source_profile("syslog-001", "1.0.0")

    with pytest.raises(ProfileNotFoundError):
        get_historical_source_profile("syslog-001", "1.0.0")

    registered = [src for src, _, _ in list_source_profiles()]
    assert "syslog-001" not in registered, (
        "syslog-001 must remain strictly unregistered"
    )


# ---------------------------------------------------------------------------
# TEST 4 — Full 7-event demo pipeline with OCSF PASS
# ---------------------------------------------------------------------------

def test_demo_pipeline_full_ocsf_pass(
    raw_demo_bytes, registered_demo_profile, demo_parser, ground_truth
):
    """
    Full pipeline: ingest → parse → Source Context inject → OCSF map → validate.

    Expected: OCSF validation PASS for all 7 events.
    Ground truth verified for key OCSF fields.
    """
    mapper = OCSFMapper()
    records = split_raw_records(raw_demo_bytes)
    assert len(records) == DEMO_EVENT_COUNT

    for i, (rec_idx, offset_start, offset_end, record_bytes) in enumerate(records):
        # 1. Raw byte preservation
        assert len(record_bytes) > 0, f"Event {i+1}: empty record bytes"

        # 2. Ingest raw bytes
        event = ingest_bytes(
            record_bytes,
            source_id=DEMO_FIXTURE_ID,
            input_format="syslog",
            profile_version=DEMO_PROFILE_VERSION,
            byte_offset_start=offset_start,
            byte_offset_end=offset_end,
            record_index=rec_idx,
        )

        # 3. SHA-256 integrity
        expected_hash = hashlib.sha256(record_bytes).hexdigest()
        assert event.sha256 == expected_hash, (
            f"Event {i+1}: SHA-256 mismatch after ingestion"
        )
        assert vault.verify(event.locator) is True, (
            f"Event {i+1}: vault integrity verification failed"
        )
        assert event.integrity_status == "verified", (
            f"Event {i+1}: expected integrity 'verified', got '{event.integrity_status}'"
        )

        # 4. vault metadata carries profile_version
        meta = vault.metadata(event.locator)
        assert meta.profile_version == DEMO_PROFILE_VERSION, (
            f"Event {i+1}: vault metadata must persist profile_version"
        )
        assert meta.source_id == DEMO_FIXTURE_ID

        # 5. Parse — strip line terminator for text parser
        text = strip_record_terminator(record_bytes).decode("utf-8").strip()
        parsed_fields = demo_parser.parse(text)
        assert parsed_fields, f"Event {i+1}: parser returned empty fields"

        # 6. Map with Source Profile context injection
        raw_mapped = mapper.map_syslog(
            parsed_fields,
            source_id=DEMO_FIXTURE_ID,
            profile_version=DEMO_PROFILE_VERSION,
        )

        # 7. Enrich OCSF headers
        enriched = mapper.enrich_ocsf_headers(parsed_fields, raw_mapped)

        # 8. OCSF validation — MUST PASS
        val_result = mapper.validator.validate(enriched)
        assert isinstance(val_result, OCSFValidationResult)
        assert val_result.ocsf_version == "1.3.0"
        assert val_result.is_valid is True, (
            f"Event {i+1}: OCSF validation must PASS for demo fixture "
            f"(all required fields supplied by Source Profile). "
            f"Errors: {[e.to_dict() for e in val_result.errors]}"
        )

        # 9. Policy field values
        for field, expected_val in POLICY_VALUES.items():
            assert field in enriched, f"Event {i+1}: policy field '{field}' missing"
            assert enriched[field] == expected_val, (
                f"Event {i+1}: policy field '{field}' expected {expected_val}, "
                f"got {enriched[field]}"
            )

        # 10. Authoritative timestamp from Source Profile — no fallback
        assert "time" in enriched, (
            f"Event {i+1}: 'time' must be present (supplied by Source Profile)"
        )
        assert enriched["time"] == EXPECTED_TIMESTAMPS[i], (
            f"Event {i+1}: timestamp mismatch.\n"
            f"  Expected (ground truth): {EXPECTED_TIMESTAMPS[i]}\n"
            f"  Actual:                  {enriched['time']}"
        )

        # 11. Authoritative metadata from Source Profile — no fallback
        assert "metadata" in enriched, (
            f"Event {i+1}: 'metadata' must be present (supplied by Source Profile)"
        )
        assert enriched["metadata"]["product"]["vendor_name"] == "Linux", (
            f"Event {i+1}: vendor_name must come ONLY from Source Profile"
        )
        assert enriched["metadata"]["product"]["name"] == "iptables", (
            f"Event {i+1}: product name must come ONLY from Source Profile"
        )

        # 12. Provenance: source profile id on MappingResult
        assert isinstance(enriched, MappingResult), (
            f"Event {i+1}: mapper must return MappingResult"
        )
        assert enriched.source_profile_id == f"{DEMO_FIXTURE_ID}:{DEMO_PROFILE_VERSION}", (
            f"Event {i+1}: MappingResult must record source_profile_id"
        )
        assert enriched.source_profile_version == DEMO_PROFILE_VERSION

        # 13. Injected fields provenance lineage
        injected_names = {f["field"] for f in enriched.injected_fields}
        assert "time" in injected_names, (
            f"Event {i+1}: 'time' must be recorded as injected from source_profile"
        )
        assert "metadata" in injected_names, (
            f"Event {i+1}: 'metadata' must be recorded as injected from source_profile"
        )
        for inj in enriched.injected_fields:
            assert inj.get("source") == "source_profile", (
                f"Event {i+1}: injected field '{inj['field']}' source must be "
                f"'source_profile', got '{inj.get('source')}'"
            )
            assert inj.get("profile_id") == f"{DEMO_FIXTURE_ID}:{DEMO_PROFILE_VERSION}"

        # 14. Ground truth key field verification
        gt_event = ground_truth[i]
        gt_ocsf = gt_event["expected_ocsf"]
        assert enriched["time"] == gt_ocsf["time"], (
            f"Event {i+1}: time does not match ground truth"
        )
        assert enriched["metadata"]["product"]["vendor_name"] == gt_ocsf["metadata"]["product"]["vendor_name"]
        assert enriched["metadata"]["product"]["name"] == gt_ocsf["metadata"]["product"]["name"]
        assert enriched["connection_info"]["protocol_name"] == gt_ocsf["connection_info"]["protocol_name"]
        assert enriched["connection_info"]["direction_id"] == gt_ocsf["connection_info"]["direction_id"], (
            f"Event {i+1}: direction_id mismatch vs ground truth. "
            f"Expected {gt_ocsf['connection_info']['direction_id']}, "
            f"got {enriched['connection_info']['direction_id']}"
        )
        if "src_endpoint" in gt_ocsf and "ip" in gt_ocsf["src_endpoint"]:
            assert enriched.get("src_endpoint", {}).get("ip") == gt_ocsf["src_endpoint"]["ip"]
        if "dst_endpoint" in gt_ocsf and "ip" in gt_ocsf["dst_endpoint"]:
            assert enriched.get("dst_endpoint", {}).get("ip") == gt_ocsf["dst_endpoint"]["ip"]

        # 15. No fabricated current-year or local-timezone fallbacks present
        # Absence of these guard assertions proves the framework's policy holds.
        # (If capture_year/timezone were missing, time would be absent — and
        # validation would FAIL. The PASS above proves they came from the profile.)


# ---------------------------------------------------------------------------
# TEST 5 — Deterministic output across repeated runs
# ---------------------------------------------------------------------------

def test_demo_pipeline_deterministic(
    raw_demo_bytes, registered_demo_profile, demo_parser
):
    """Same input + same profile → identical normalized output on every run."""
    mapper = OCSFMapper()
    records = split_raw_records(raw_demo_bytes)

    run1, run2 = [], []
    for (_, _, _, record_bytes) in records:
        text = strip_record_terminator(record_bytes).decode("utf-8").strip()
        fields = demo_parser.parse(text)
        evt = mapper.enrich_ocsf_headers(
            fields,
            mapper.map_syslog(
                fields,
                source_id=DEMO_FIXTURE_ID,
                profile_version=DEMO_PROFILE_VERSION,
            )
        )
        run1.append(dict(evt))

    for (_, _, _, record_bytes) in records:
        text = strip_record_terminator(record_bytes).decode("utf-8").strip()
        fields = demo_parser.parse(text)
        evt = mapper.enrich_ocsf_headers(
            fields,
            mapper.map_syslog(
                fields,
                source_id=DEMO_FIXTURE_ID,
                profile_version=DEMO_PROFILE_VERSION,
            )
        )
        run2.append(dict(evt))

    assert run1 == run2, "Normalized output must be deterministic across repeated runs"


# ---------------------------------------------------------------------------
# TEST 6 — Replay verification (Phase 7)
# ---------------------------------------------------------------------------

def test_demo_replay_after_deactivation(
    raw_demo_bytes, registered_demo_profile, demo_parser
):
    """
    Verify historical replay after profile deactivation.

    Sequence:
      1. Normalize using active profile 1.0.0.
      2. Deactivate profile 1.0.0.
      3. Confirm normal ingestion lookup rejects it.
      4. Confirm historical lookup still retrieves it.
      5. Replay — deterministic normalization without reactivation.
    """
    mapper = OCSFMapper()
    records = split_raw_records(raw_demo_bytes)
    first_record_bytes = records[0][3]
    text = strip_record_terminator(first_record_bytes).decode("utf-8").strip()
    parsed_fields = demo_parser.parse(text)

    # Step 1: Normalize while active
    original_event = mapper.enrich_ocsf_headers(
        parsed_fields,
        mapper.map_syslog(
            parsed_fields,
            source_id=DEMO_FIXTURE_ID,
            profile_version=DEMO_PROFILE_VERSION,
        )
    )
    assert original_event.get("time") == EXPECTED_TIMESTAMPS[0]

    # Step 2: Deactivate
    deactivate_source_profile(DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION)

    # Step 3: Normal ingestion lookup must reject
    with pytest.raises(ProfileInactiveError):
        get_source_profile(DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION)

    # Step 4: Historical lookup must succeed
    historical_profile = get_historical_source_profile(DEMO_FIXTURE_ID, DEMO_PROFILE_VERSION)
    assert historical_profile == DEMO_PROFILE

    # Step 5: Replay produces deterministic output without reactivation
    replayed = mapper.replay_syslog(
        parsed_fields,
        source_id=DEMO_FIXTURE_ID,
        profile_version=DEMO_PROFILE_VERSION,
    )
    replayed_enriched = mapper.enrich_ocsf_headers(parsed_fields, replayed)

    assert replayed_enriched.get("time") == EXPECTED_TIMESTAMPS[0], (
        "Replay must produce identical timestamp as original normalization"
    )
    assert replayed_enriched["metadata"]["product"]["vendor_name"] == "Linux", (
        "Replay must resolve vendor from historical profile, not active profile"
    )
    assert dict(replayed_enriched) == dict(original_event), (
        "Replay output must be byte-for-byte identical to original normalization"
    )


# ---------------------------------------------------------------------------
# TEST 7 — profile_version persisted in vault metadata
# ---------------------------------------------------------------------------

def test_demo_profile_version_in_vault_metadata(
    raw_demo_bytes, registered_demo_profile
):
    """Vault metadata must persist profile_version for each ingested record."""
    records = split_raw_records(raw_demo_bytes)
    for i, (rec_idx, offset_start, offset_end, record_bytes) in enumerate(records):
        event = ingest_bytes(
            record_bytes,
            source_id=DEMO_FIXTURE_ID,
            input_format="syslog",
            profile_version=DEMO_PROFILE_VERSION,
            byte_offset_start=offset_start,
            byte_offset_end=offset_end,
            record_index=rec_idx,
        )
        meta = vault.metadata(event.locator)
        assert meta.profile_version == DEMO_PROFILE_VERSION, (
            f"Event {i+1}: vault metadata must persist profile_version"
        )
        assert meta.source_id == DEMO_FIXTURE_ID
        assert meta.record_index == rec_idx
        assert meta.byte_offset_start == offset_start
        assert meta.byte_offset_end == offset_end


# ---------------------------------------------------------------------------
# TEST 8 — Raw byte chain integrity across all 7 events
# ---------------------------------------------------------------------------

def test_demo_raw_chain_integrity(raw_demo_bytes, registered_demo_profile):
    """Chain integrity must hold after ingesting all 7 demo events."""
    records = split_raw_records(raw_demo_bytes)
    locators = []

    for (rec_idx, offset_start, offset_end, record_bytes) in records:
        event = ingest_bytes(
            record_bytes,
            source_id=DEMO_FIXTURE_ID,
            input_format="syslog",
            profile_version=DEMO_PROFILE_VERSION,
            byte_offset_start=offset_start,
            byte_offset_end=offset_end,
            record_index=rec_idx,
        )
        locators.append(event.locator)
        assert vault.verify(event.locator) is True

    # Chain must verify after all 7 records ingested
    backend = vault._BACKEND
    if hasattr(backend, "verify_chain"):
        assert backend.verify_chain() is True, "Vault chain must verify after 7-event demo ingestion"

    # Verify round-trip raw bytes for each record
    all_original = split_raw_records(raw_demo_bytes)
    for locator, (_, _, _, original_bytes) in zip(locators, all_original):
        stored = vault.get(locator)
        assert stored == original_bytes, "Stored raw bytes must be byte-for-byte identical to original"


# ---------------------------------------------------------------------------
# TEST 9 — syslog-001 original SHA-256 is unchanged
# ---------------------------------------------------------------------------

def test_syslog_001_fixture_sha256_unchanged():
    """The historical syslog-001 fixture must not have been touched."""
    real_path = Path("fixtures/raw/syslog/syslog-001.log").resolve()
    with open(real_path, "rb") as f:
        data = f.read()
    sha256 = hashlib.sha256(data).hexdigest()
    assert sha256 == "a3783b7c387f7248d8c90c315b9b06a73bf4f7e6d0a6631b0a2449afd5706552", (
        "syslog-001 raw fixture must remain byte-for-byte unchanged"
    )
    assert len(data) == 5330, "syslog-001 byte length must remain unchanged"
